IF
  Global("C0AutoCreated", "GLOBAL", 0)
  ClassLevelLT("C0AURA",ROGUE,14)  // Aura
THEN RESPONSE #100
  SetInterrupt(FALSE)
  SetGlobal("SPRITE_IS_DEADC0AUIN3","GLOBAL",0)
  SetGlobal("C0AutoCreated", "GLOBAL", 1)
  ActionOverride("C0AURA",ReallyForceSpellRES("c0auin3a",Myself))
  SetInterrupt(TRUE)
  DestroySelf()
END

IF
  Global("C0AutoCreated", "GLOBAL", 0)
    ClassLevelGT("C0AURA",ROGUE,13)  // Aura
    ClassLevelLT("C0AURA",ROGUE,22)  // Aura
THEN RESPONSE #100
  SetInterrupt(FALSE)
  SetGlobal("SPRITE_IS_DEADC0AUIN3","GLOBAL",0)
  SetGlobal("C0AutoCreated", "GLOBAL", 1)
  ActionOverride("C0AURA",ReallyForceSpellRES("c0auin3B",Myself))
  SetInterrupt(TRUE)
  DestroySelf()
END

IF
  Global("C0AutoCreated", "GLOBAL", 0)
  ClassLevelGT("C0AURA",ROGUE,21)  // Aura
THEN RESPONSE #100
  SetInterrupt(FALSE)
  SetGlobal("SPRITE_IS_DEADC0AUIN3","GLOBAL",0)
  SetGlobal("C0AutoCreated", "GLOBAL", 1)
  ActionOverride("C0AURA",ReallyForceSpellRES("c0auin3C",Myself))
  SetInterrupt(TRUE)
  DestroySelf()
END

IF
  Global("C0AutoCreated", "GLOBAL", 1)
  OR(2)
  !HPLT("C0AUIN3",1)
  Dead("C0AUIN3")
THEN RESPONSE #100
  SetGlobal("C0AutoCreated", "GLOBAL", 0)
  Continue()
END

IF
  Global("C0AutoCreated", "GLOBAL", 1)
  !Dead("C0AUIN3")
  InMyArea("C0AUIN3")
THEN RESPONSE #100
	DisplayString("C0AURA",~An automaton is already currently active.~)
	DestroySelf()
END

IF
  Global("C0AutoCreated", "GLOBAL", 1)
  !Dead("C0AUIN3")
  !InMyArea("C0AUIN3")
THEN RESPONSE #100
	MoveGlobalObject("C0AUIN3","C0AURA")
	DisplayString("C0AURA",~An automaton is already currently active.~)
	DestroySelf()
END